name: Workflow for my hello world title
on: push

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: /action-a
        with:
            MY_NAME: "Georgy"